"""
Zwift Workout Catalog for IronCoach AI.
SST und Tempo sind eine Kategorie ('sst_tempo').
Styles: sst_tempo | subthreshold | cadence | vo2_transition | endurance | threshold | vo2max
"""

ZWIFT_CATALOG = [
    {
        "name": "Sweet Spot Ramps - 30min",
        "duration_min": 30,
        "tss": 11,
        "style": "sst_tempo",
        "phases": ["Base 1", "Base 2"],
        "key_blocks": "Ramp-Aufbau 65→91% FTP @89rpm, akkumuliert 30min Sweet Spot",
        "note": "Idealer Einstieg, gut für Deload oder erste SST-Einheiten",
    },
    {
        "name": "Free Ride Sandwich",
        "duration_min": 47,
        "tss": 13,
        "style": "sst_tempo",
        "phases": ["Base 1", "Base 2"],
        "key_blocks": "3×10min @85% FTP, mittlerer Block als Free Ride (Z3 frei)",
        "note": "Gut für mentale Abwechslung, Deload-freundlich",
    },
    {
        "name": "Strength Endurance + REV 15sec",
        "duration_min": 43,
        "tss": 41,
        "style": "cadence",
        "phases": ["Base 1", "Base 2", "Base 3"],
        "key_blocks": "3×5min @65rpm 85% FTP + 15sec @100% FTP Sprints, 2min Pause",
        "note": "Muskelkraft + kurze neuromuskuläre Aktivierung, ruhige Oberkörperhaltung",
    },
    {
        "name": "Sweet Spot Builds",
        "duration_min": 60,
        "tss": 62,
        "style": "sst_tempo",
        "phases": ["Base 1", "Base 2", "Base 3"],
        "key_blocks": "Mikro-Aufbau-Intervalle: 10sec @80%→90%→100% FTP, 1min @60%, 3min @88% FTP, wiederholt",
        "note": "Gut für Recovery-Wochen, kein maximaler Stress aber viel Zeit im Sweet Spot",
    },
    {
        "name": "Sweet Spot Pyramid - 50min",
        "duration_min": 50,
        "tss": 50,
        "style": "sst_tempo",
        "phases": ["Base 2", "Base 3"],
        "key_blocks": "Pyramide: 2→4→6→8→10→8→6→4→2min @80-88% FTP @89rpm",
        "note": "Symmetrische Belastung, mentaler Vorteil durch abnehmende Blöcke",
    },
    {
        "name": "Big Gear SST - 3x5",
        "duration_min": 35,
        "tss": 37,
        "style": "cadence",
        "phases": ["Base 2", "Base 3"],
        "key_blocks": "3×5min @75rpm 88-95% FTP, 2:30min @90rpm 65% FTP Pause",
        "note": "Big Gear = hoher Widerstand bei niedriger Kadenz, Muskelkraftfokus",
    },
    {
        "name": "SST Bursts 8",
        "duration_min": 30,
        "tss": 45,
        "style": "sst_tempo",
        "phases": ["Base 3"],
        "key_blocks": "SST-Basis @85% FTP mit 8×High-Torque-Bursts @105% FTP (30sec on/off)",
        "note": "Kurze Einheit, hoher neuromuskulärer Reiz",
    },
    {
        "name": "Sweet Spot",
        "duration_min": 55,
        "tss": 60,
        "style": "sst_tempo",
        "phases": ["Base 3", "Build 1"],
        "key_blocks": "20min @85-91% FTP @90rpm, dann 5×1min @100% FTP mit 2min Pause",
        "note": "Klassisches SST-Format, Finisher-Blöcke trainieren Schwelle",
    },
    {
        "name": "Pounding Sand",
        "duration_min": 58,
        "tss": 53,
        "style": "sst_tempo",
        "phases": ["Base 3", "Build 1"],
        "key_blocks": "2×1min @90%, 4min @70%, 4min @80% FTP warm-up, dann 3×6min @80rpm 75-88% FTP",
        "note": "Progressiver Aufbau, Hauptblöcke mit stabiler Kadenz",
    },
    {
        "name": "Tempo",
        "duration_min": 60,
        "tss": 55,
        "style": "sst_tempo",
        "phases": ["Base 3", "Build 1"],
        "key_blocks": "4×8min @85% FTP @80rpm, 3min @50% FTP Pause",
        "note": "Standard-Tempo, Z3-fokussiert, einfach zu skalieren",
    },
    {
        "name": "Tempo #1",
        "duration_min": 51,
        "tss": 55,
        "style": "sst_tempo",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "2×20min Tempo-Blöcke @76-89% FTP, 5min @50% FTP Pause",
        "note": "Längere Blöcke für aerobe Ausdauer, Klassiker",
    },
    {
        "name": "Dirty Teeth Drills",
        "duration_min": 79,
        "tss": 58,
        "style": "sst_tempo",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "4:30min @78% FTP + 30sec @100% FTP Burst, 3min @55% FTP, 6× wiederholt",
        "note": "Variable Intensität verbessert FTP-Nutzung als Brennstoff; UNBOUND-spezifisch",
    },
    {
        "name": "Recipe for Grit",
        "duration_min": 54,
        "tss": 54,
        "style": "cadence",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "3×(5min @75rpm + 5min @80rpm + 5min @85rpm) @76-89% FTP, 3min @50% Pause",
        "note": "Kadenz steigt alle 5min, trainiert muskuläre Ausdauer bei unterschiedlichen RPM",
    },
    {
        "name": "15min Varied Tempo #2",
        "duration_min": 78,
        "tss": 62,
        "style": "cadence",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "5min Blöcke abwechselnd: 95rpm @89% FTP und 90rpm @77% FTP, 3× mit 3min Pause",
        "note": "Kadenz- und Leistungsvariation, HR-Reaktion auf RPM-Wechsel beobachten",
    },
    {
        "name": "Rolling Roads",
        "duration_min": 90,
        "tss": 70,
        "style": "sst_tempo",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "3×15min Tempo @76-89% FTP (kurze Rampen von Z3-Unter zu Z3-Ober), 10sec @150% FTP Sprint am Ende jedes Blocks",
        "note": "Längste Tempo-Einheit im Katalog, abschließender Sprint hält top-end aktiv",
    },
    {
        "name": "Sepp Kuss Cadence Efforts",
        "duration_min": 58,
        "tss": 62,
        "style": "cadence",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "3×(4min @60rpm 85% FTP + 1min @100rpm 100% FTP), 2min @55% FTP Pause",
        "note": "Extremer Kadenzwechsel 60→100rpm, rekrutiert unterschiedliche Muskelfasern",
    },
    {
        "name": "Sub Threshold #4",
        "duration_min": 70,
        "tss": 94,
        "style": "subthreshold",
        "phases": ["Build 1", "Build 2", "Build 3"],
        "key_blocks": "2×20min @88% FTP, dann 8×(1min @110% FTP + 1min @55% FTP)",
        "note": "Hoher TSS! Nur bei grüner HRV. Sub-Threshold-Blöcke + Threshold-Bursts",
    },
    {
        "name": "Texaco Hill Tempo",
        "duration_min": 59,
        "tss": 50,
        "style": "sst_tempo",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "3×(6min @80rpm 75-88% FTP + 6min @90rpm 75-85% FTP), 2min @50% Pause",
        "note": "Alternierende Kadenz simuliert Hügel, Ausdauer unter Ermüdung",
    },
    {
        "name": "Tempo 15min Target RPM #3",
        "duration_min": 70,
        "tss": 71,
        "style": "cadence",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "3×(5min @75rpm + 5min @80rpm + 5min @85rpm) @76-89% FTP, 2min Pause",
        "note": "Kadenz erhöht sich alle 5min pro Block, aerobe Effizienz bei hohem RPM",
    },
    {
        "name": "Tempo Climbing",
        "duration_min": 60,
        "tss": 59,
        "style": "sst_tempo",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "4×(4min @75-85% FTP ramp + 30sec @165% FTP Burst), 3min @50% Pause",
        "note": "Simuliert Anstiege mit Over-Threshold-Surges, Laktat-Clearance trainieren",
    },
    {
        "name": "Tempo with Accelerations #1",
        "duration_min": 52,
        "tss": 63,
        "style": "sst_tempo",
        "phases": ["Build 3", "Peak 1", "Peak 2"],
        "key_blocks": "3×(4min @90rpm 84% FTP + 15sec @175% FTP + 4min @84% FTP + 20sec @170% FTP + 4min @84% FTP + 30sec @150% FTP), 5min @50% Pause",
        "note": "Sprints wachsen von 15→20→30sec innerhalb jedes Blocks, race-spezifisch",
    },
    {
        "name": "Tempo into VO2 Max #1",
        "duration_min": 60,
        "tss": 65,
        "style": "vo2_transition",
        "phases": ["Build 3", "Peak 1", "Peak 2"],
        "key_blocks": "3min @65% + 4min @60% + 3min @75% Tempo-Basis, dann 3×(3min @112% FTP + 2min @55%)",
        "note": "Tempo depleted energy stores zuerst, dann VO2max-Intervalle — härtere Adaption",
    },
    {
        "name": "Sweet Spot 12",
        "duration_min": 31,
        "tss": 71,
        "style": "vo2_transition",
        "phases": ["Build 3", "Peak 1", "Peak 2"],
        "key_blocks": "2×12min SST @80rpm, dann 4×3min VO2max @80rpm @125% FTP",
        "note": "Kurz aber intensiv, SST-Vorbereitung macht VO2max-Blöcke schwerer",
    },
    {
        "name": "Explosive SST #2",
        "duration_min": 115,
        "tss": 104,
        "style": "vo2_transition",
        "phases": ["Peak 1", "Peak 2"],
        "key_blocks": "Aufwärm-Pyramide, dann 3×(15min SST @90% FTP + 3×15sec @140% FTP Sprints am Anfang), 10min Pause",
        "note": "Sehr hoher TSS! Nur Peak-Phasen, grüne HRV Pflicht. Längste Einheit im Katalog",
    },
]

# ── ENDURANCE ────────────────────────────────────────────────────────────────
ENDURANCE_CATALOG = [
    {
        "name": "Cafe Ride",
        "duration_min": 34,
        "tss": 27,
        "style": "endurance",
        "phases": ["Base 1"],
        "key_blocks": "Entspannter Z1-Z2 Ride, sehr niedrige Intensität 45-80% FTP",
        "note": "Aktive Erholung, ideal nach harten Tagen oder als Opener",
    },
    {
        "name": "Z2 Cadence Changes",
        "duration_min": 50,
        "tss": 32,
        "style": "endurance",
        "phases": ["Base 1", "Base 2"],
        "key_blocks": "10min Aufwärmen, 30min Z2 @65% FTP mit 20sec @110rpm-Kadenz jede Minute",
        "note": "Aerobe Basis + Kadenzkontrolle, sehr schonend",
    },
    {
        "name": "High-Cadence Builds",
        "duration_min": 47,
        "tss": 33,
        "style": "endurance",
        "phases": ["Base 1", "Base 2"],
        "key_blocks": "3×9min: 6× durch 30sec @90rpm/30sec @100rpm/30sec @110rpm (Z1-Z3), 3min Pause",
        "note": "Recovery-Fokus mit RPM-Drill, kein Powerstress",
    },
    {
        "name": "Aerobic Sustainability",
        "duration_min": 50,
        "tss": 50,
        "style": "endurance",
        "phases": ["Base 1", "Base 2"],
        "key_blocks": "Steady Z3-Block @80% FTP, kurze Z4-Spitzen @95% FTP",
        "note": "Grundlagenausdauer, einfache Struktur",
    },
    {
        "name": "Taper Steady",
        "duration_min": 50,
        "tss": 51,
        "style": "endurance",
        "phases": ["Base 1", "Base 2", "Peak 1", "Peak 2"],
        "key_blocks": "Z2-Z3 Steady @65-80% FTP, kurze Z4-Blöcke @100% FTP eingebaut",
        "note": "Taper-Einheit: hält Rhythmus ohne Ermüdung, auch pre-race",
    },
    {
        "name": "Endurance #1",
        "duration_min": 60,
        "tss": 52,
        "style": "endurance",
        "phases": ["Base 2", "Base 3"],
        "key_blocks": "Aerobe Basis @70% FTP, alle 5min 10sec-Surge @130% FTP",
        "note": "Lange Z2-Basis mit neuromuskulären Spitzen",
    },
    {
        "name": "Get It Done",
        "duration_min": 60,
        "tss": 49,
        "style": "endurance",
        "phases": ["Base 2", "Base 3"],
        "key_blocks": "3×12min alternierend Z2/Z3 @70-80% FTP, 1min Free Ride am Ende jedes Blocks",
        "note": "Klassisches Ausdauerformat, sauber und effektiv",
    },
    {
        "name": "Rolling Hills #1",
        "duration_min": 56,
        "tss": 49,
        "style": "endurance",
        "phases": ["Base 2", "Base 3"],
        "key_blocks": "Wiederholte 2-3min Efforts @Z3 mit niedriger Kadenz, simuliert Außentraining",
        "note": "Kadenz variiert wie auf echten Hügeln, gut für Outdoor-Vorbereitung",
    },
    {
        "name": "Pacing #1",
        "duration_min": 58,
        "tss": 59,
        "style": "endurance",
        "phases": ["Base 2", "Base 3"],
        "key_blocks": "Steady-State Intervalle unter Schwelle, Z2-Z3 @75-88% FTP",
        "note": "Pacing-Training: Intensität nach Gefühl regulieren ohne auf Daten zu schauen",
    },
    {
        "name": "Endurance #3",
        "duration_min": 66,
        "tss": 60,
        "style": "endurance",
        "phases": ["Base 3", "Build 1"],
        "key_blocks": "High-Cadence Intervalle @110rpm eingebaut in Z2-Basis, kurze Z4-Blöcke",
        "note": "Kardioausdauer + Kadenzfokus kombiniert",
    },
    {
        "name": "Pacing #2",
        "duration_min": 68,
        "tss": 65,
        "style": "endurance",
        "phases": ["Base 3", "Build 1"],
        "key_blocks": "Längere Steady-State Blöcke @75-88% FTP Z2-Z3, Progression über 5min-Blöcke",
        "note": "Erweiterte Pacing #1, mehr Gesamtvolumen",
    },
    {
        "name": "Saw Legs",
        "duration_min": 77,
        "tss": 75,
        "style": "endurance",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "3×15min Z3-Blöcke mit kurzen Rampen, mittlerer Block @65rpm, kurze Sprints",
        "note": "Ausdauer mit Kadenzvariation, MTB-spezifisch",
    },
    {
        "name": "Aerobic Builds",
        "duration_min": 90,
        "tss": 82,
        "style": "endurance",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "3×(4×1min @85%) + 3×(3min Aufbau 60→90% FTP), 4×4min @80% FTP Finale",
        "note": "Lange Einheit, Snack empfohlen. Kein Upjustieren der Watts!",
    },
    {
        "name": "Workout 16",
        "duration_min": 82,
        "tss": 88,
        "style": "endurance",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "Pyramide bis 2min @109% FTP @70rpm, simuliert Laktat-Toleranz unter Ermüdung",
        "note": "All-Round Einheit mit Kadenz- und Intensitätswechsel, Laktattoleranz",
    },
    {
        "name": "The Long Ride",
        "duration_min": 85,
        "tss": 96,
        "style": "endurance",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "Lange Basistour Z2 @65% FTP mit Z4-Blöcken @95-105% FTP eingebaut",
        "note": "Höchster TSS der Endurance-Kategorie. Nur bei guter HRV",
    },
]

# ── THRESHOLD ─────────────────────────────────────────────────────────────────
THRESHOLD_CATALOG = [
    {
        "name": "Over - Unders",
        "duration_min": 33,
        "tss": 44,
        "style": "threshold",
        "phases": ["Base 3", "Build 1"],
        "key_blocks": "3×(3min @100% + 3min @108% + 3min @90% FTP), 3min Pause",
        "note": "Klassische Over/Under-Einleitung, Laktatpufferung entwickeln",
    },
    {
        "name": "Long Tempo",
        "duration_min": 50,
        "tss": 56,
        "style": "threshold",
        "phases": ["Base 3", "Build 1"],
        "key_blocks": "Lange Tempo-Intervalle @100% FTP, 30min kontinuierliche Z4-Arbeit",
        "note": "Gewöhnung an anhaltende Schwellenbelastung für längere Anstiege",
    },
    {
        "name": "2x(4x2min) Threshold Fun",
        "duration_min": 60,
        "tss": 58,
        "style": "threshold",
        "phases": ["Base 3", "Build 1"],
        "key_blocks": "4×(40sec @80/90/100% FTP Build) + 4×2min @100% FTP, 2 Runden",
        "note": "Sanfter Schwelleneinstieg mit RPM-Fokus",
    },
    {
        "name": "Cameron Wurf: All-Rounder",
        "duration_min": 60,
        "tss": 59,
        "style": "threshold",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "3×10min Threshold @100% FTP, 1. und 10. Minute jedes Blocks @110% FTP",
        "note": "Ironman-spezifisch: breite Aerobbase + Schwellenkick",
    },
    {
        "name": "Threshold #1",
        "duration_min": 58,
        "tss": 67,
        "style": "threshold",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "Strukturierte FTP-Intervalle knapp über/unter Schwelle, ERG-Modus ideal",
        "note": "Klassisches Threshold-Format, FTP-Entwicklung",
    },
    {
        "name": "Halvfems",
        "duration_min": 62,
        "tss": 68,
        "style": "threshold",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "37min @90% FTP in Blöcken mit Kadenzvariation @60-100rpm",
        "note": "SST-Trio (mittlere Schwierigkeit), viel Zeit bei 90%",
    },
    {
        "name": "Norseman: Eidfjord",
        "duration_min": 70,
        "tss": 83,
        "style": "threshold",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "3×9min @100% FTP mit 45sec Burst @115% FTP am Start und bei 4:30min",
        "note": "Schwellenausdauer + harte Starts kombiniert, muskuläre Ausdauer",
    },
    {
        "name": "Novanta",
        "duration_min": 60,
        "tss": 70,
        "style": "threshold",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "41min @90% FTP, 5×1min @115% FTP Bursts eingebaut",
        "note": "SST-Trio (härteste Variante), hohe Zeit bei 90%",
    },
    {
        "name": "Malevolent",
        "duration_min": 60,
        "tss": 79,
        "style": "threshold",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "Abnehmende Intervalllängen @90% FTP mit 1min @115% FTP am Ende jedes Reps",
        "note": "Beginnt moderat, wird hart — dann richtig böse",
    },
    {
        "name": "Threshold Development",
        "duration_min": 66,
        "tss": 73,
        "style": "threshold",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "Kurze Z4-Intervalle mit Z3-Basis, schrittweise FTP-Erhöhung",
        "note": "FTP-Entwicklung durch wiederholte kurze Schwellenblöcke",
    },
    {
        "name": "Cruise Intervals #4",
        "duration_min": 59,
        "tss": 77,
        "style": "threshold",
        "phases": ["Build 3", "Peak 1"],
        "key_blocks": "Moderate Cruise-Intervalle Z4, wechselnde Zielleistung auf/ab innerhalb der Blöcke",
        "note": "TT-Kadenz fokus, kontrolliertes Atmen unter Belastung",
    },
    {
        "name": "Threshold #2",
        "duration_min": 66,
        "tss": 85,
        "style": "threshold",
        "phases": ["Build 3", "Peak 1"],
        "key_blocks": "2×20min @100% FTP mit kurzen Überschwellen-Bursts, 3min Pause",
        "note": "Klassisches 2×20 Format, hoher FTP-Stimulus",
    },
    {
        "name": "TT#1 The Polish",
        "duration_min": 82,
        "tss": 95,
        "style": "threshold",
        "phases": ["Peak 1", "Peak 2"],
        "key_blocks": "Komplexe TT-Vorbereitung: 33min Z4 + 9min Z5, Aufbau auf solider Aerobbase",
        "note": "Nur nach abgeschlossener Aerobbase. Grüne HRV erforderlich",
    },
    {
        "name": "Kirizuma",
        "duration_min": 90,
        "tss": 112,
        "style": "threshold",
        "phases": ["Peak 1", "Peak 2"],
        "key_blocks": "Japanisches Dach-Intervallmuster: 45min @100% FTP + 7min Z5, sehr hohe Dichte",
        "note": "Sehr hoher TSS! Nur Peak-Phase, grüne HRV Pflicht",
    },
]

# ── VO2MAX ────────────────────────────────────────────────────────────────────
VO2MAX_CATALOG = [
    {
        "name": "VO2 Max 3x3",
        "duration_min": 38,
        "tss": 47,
        "style": "vo2max",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "3×3min @110-115% FTP, 3min Pause — erster VO2max-Einstieg",
        "note": "Sanfte VO2max-Einführung, FTP-Bias per Pfeiltaste anpassen",
    },
    {
        "name": "30/30 Anaerobic #1",
        "duration_min": 52,
        "tss": 57,
        "style": "vo2max",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "8min in Z5: kurze 30/30-Intervalle über Schwelle, akkumulierte Z5-Zeit",
        "note": "Early-Base VO2 — kurze Efforts erlauben mehr Gesamtzeit über Threshold",
    },
    {
        "name": "40/20's #1",
        "duration_min": 51,
        "tss": 52,
        "style": "vo2max",
        "phases": ["Build 1", "Build 2"],
        "key_blocks": "40sec über Threshold + 20sec Pause, 10min Z5-Akkumulation total",
        "note": "Erholung-Wiederholung trainieren, HR-Reaktion über Set beobachten",
    },
    {
        "name": "6 Bombs to Drop",
        "duration_min": 58,
        "tss": 66,
        "style": "vo2max",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "2 Blöcke 3×2:30min @110% FTP (Block 1 @65rpm, Block 2 freie Kadenz), 8min Z3 dazwischen",
        "note": "MTB-Race-Simulation: harter Start + stabiles Mittelstück + harter Schluss",
    },
    {
        "name": "The Ganna",
        "duration_min": 50,
        "tss": 63,
        "style": "vo2max",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "3-5min VO2max-Blöcke @115% FTP + kurze anaerobe Bursts @130% FTP",
        "note": "Ganna-Style: 3-5min Power ist bester VO2max-Proxy",
    },
    {
        "name": "#8",
        "duration_min": 60,
        "tss": 65,
        "style": "vo2max",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "2 Blöcke 3×2min @115% FTP, Z2-Pause zwischen den Blöcken",
        "note": "Benannt nach Ordnungszahl von Sauerstoff, zweifache VO2-Intervallblöcke",
    },
    {
        "name": "Wout van Aert: VO2 Max Training",
        "duration_min": 57,
        "tss": 72,
        "style": "vo2max",
        "phases": ["Build 2", "Build 3"],
        "key_blocks": "6×2min @120% FTP + anaerobe Kurzblöcke, 13min Z6-Anteile",
        "note": "Belegt FTP-Steigerung: Z5 wirkt auf aerobe Kapazität",
    },
    {
        "name": "6x2 VO2 Max",
        "duration_min": 62,
        "tss": 77,
        "style": "vo2max",
        "phases": ["Build 3", "Peak 1"],
        "key_blocks": "6×2min @120% FTP, 2min Pause — sehr hohe VO2-Zone",
        "note": "Härteste kurze Dauerleistung im Plan. Hohe RPMs helfen",
    },
    {
        "name": "LOX",
        "duration_min": 60,
        "tss": 78,
        "style": "vo2max",
        "phases": ["Build 3", "Peak 1"],
        "key_blocks": "Z5-Intervallblöcke @110-120% FTP + anhaltende Z4-Basis, Raketenantrieb-Schema",
        "note": "Liquid Oxygen: kombiniert VO2max mit Threshold-Unterbau",
    },
    {
        "name": "Microbursts",
        "duration_min": 60,
        "tss": 88,
        "style": "vo2max",
        "phases": ["Build 3", "Peak 1"],
        "key_blocks": "3 Blöcke 20×15sec @160% FTP / 15sec @55% FTP, 5min Z2 dazwischen",
        "note": "Mikrointervalle: schnelle Gangwechsel zu jeder Zeit der Saison",
    },
    {
        "name": "Power Intervals #1",
        "duration_min": 56,
        "tss": 89,
        "style": "vo2max",
        "phases": ["Peak 1", "Peak 2"],
        "key_blocks": "2 Sätze kurze Hochleistungsintervalle @120%+ FTP @85rpm, dann freie Kadenz",
        "note": "Drehmoment + Muskelausdauer: Big Gear bei 85rpm dann freier Spin",
    },
    {
        "name": "Max Aerobic x 3",
        "duration_min": 97,
        "tss": 120,
        "style": "vo2max",
        "phases": ["Peak 2"],
        "key_blocks": "2 Sätze 3×5min @112%/109%/105% FTP, 5min Pause, Free Ride zwischen Sets",
        "note": "Höchster TSS aller VO2max-Einheiten. Nur Peak 2, grüne HRV absolut Pflicht",
    },
]


ALL_CATALOGS = {
    "sst_tempo": ZWIFT_CATALOG,
    "endurance": ENDURANCE_CATALOG,
    "threshold": THRESHOLD_CATALOG,
    "vo2max": VO2MAX_CATALOG,
}


def get_phase_workouts(phase: str, is_deload: bool = False, category: str = "sst_tempo") -> str:
    """
    Gibt eine kompakte Textliste der passenden Workouts für die aktuelle Phase zurück.
    category: 'sst_tempo' | 'endurance' | 'threshold' | 'vo2max' | 'all'
    Bei Deload-Wochen: nur Workouts mit TSS < 60.
    """
    catalog = []
    if category == "all":
        for c in ALL_CATALOGS.values():
            catalog.extend(c)
    else:
        catalog = ALL_CATALOGS.get(category, ZWIFT_CATALOG)

    if is_deload:
        candidates = [w for w in catalog if w["tss"] < 60 and (
            phase in w["phases"] or "Base 3" in w["phases"] or "Base 2" in w["phases"]
        )]
    else:
        candidates = [w for w in catalog if phase in w["phases"]]

    if not candidates:
        candidates = [w for w in catalog if w["tss"] <= 65]

    lines = []
    for w in candidates:
        lines.append(
            f"**{w['name']}** ({w['duration_min']}min, ~{w['tss']} TSS)\n"
            f"  → {w['key_blocks']}\n"
            f"  💡 {w['note']}"
        )

    return "\n\n".join(lines)
